/**
 * Script per configurare un account Amazon SP-API
 *
 * Uso: node setup-account.js
 */

const readline = require('readline');
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n╔════════════════════════════════════════════════════════════╗');
  console.log('║   Setup Account Amazon SP-API - Sellerboard Clone          ║');
  console.log('╚════════════════════════════════════════════════════════════╝\n');

  console.log('📝 Inserisci le informazioni del tuo account Amazon Seller:\n');

  // Seller ID
  const sellerId = await question('1. Amazon Seller ID (es: A2EUQ1WTGCTBG2): ');

  // Region
  console.log('\n2. Regione:');
  console.log('   - na: Nord America (US, CA, MX, BR)');
  console.log('   - eu: Europa (UK, DE, FR, IT, ES, NL, etc.)');
  console.log('   - fe: Far East (JP, AU, SG, etc.)');
  const region = await question('   Scegli regione (na/eu/fe): ');

  // Marketplace
  console.log('\n3. Marketplace ID:');
  if (region === 'na') {
    console.log('   - ATVPDKIKX0DER: United States');
    console.log('   - A2EUQ1WTGCTBG2: Canada');
    console.log('   - A1AM78C64UM0Y8: Mexico');
    console.log('   - A2Q3Y263D00KWC: Brazil');
  } else if (region === 'eu') {
    console.log('   - A1F83G8C2ARO7P: United Kingdom');
    console.log('   - A1PA6795UKMFR9: Germany');
    console.log('   - A13V1IB3VIYZZH: France');
    console.log('   - APJ6JRA9NG5V4: Italy');
    console.log('   - A1RKKUPIHCS9HS: Spain');
  } else if (region === 'fe') {
    console.log('   - A1VC38T7YXB528: Japan');
    console.log('   - A39IBJ37TRP1C6: Australia');
    console.log('   - A19VAU5U5O7RUS: Singapore');
  }
  const marketplaceId = await question('   Inserisci Marketplace ID: ');

  // SP-API Credentials
  console.log('\n4. Credenziali SP-API (dal Developer Central):');
  const clientId = await question('   Client ID: ');
  const clientSecret = await question('   Client Secret: ');
  const refreshToken = await question('   Refresh Token: ');

  // Calcola expiry (1 anno da ora)
  const expiresAt = new Date();
  expiresAt.setFullYear(expiresAt.getFullYear() + 1);

  console.log('\n\n🔄 Creazione account nel database...\n');

  try {
    const account = await prisma.account.create({
      data: {
        sellerId: sellerId.trim(),
        marketplaceId: marketplaceId.trim(),
        accessToken: '', // Will be generated by SDK
        refreshToken: refreshToken.trim(),
        expiresAt: expiresAt,
        region: region.trim(),
      }
    });

    console.log('✅ Account creato con successo!\n');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('Account ID:', account.id);
    console.log('Seller ID:', account.sellerId);
    console.log('Region:', account.region);
    console.log('Marketplace:', account.marketplaceId);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    // Aggiorna anche il .env
    console.log('📝 Aggiorno il file .env con le credenziali...\n');

    const fs = require('fs');
    const envPath = __dirname + '/.env';
    let envContent = fs.readFileSync(envPath, 'utf8');

    envContent = envContent
      .replace(/AMAZON_CLIENT_ID=.*/, `AMAZON_CLIENT_ID=${clientId}`)
      .replace(/AMAZON_CLIENT_SECRET=.*/, `AMAZON_CLIENT_SECRET=${clientSecret}`)
      .replace(/AMAZON_REFRESH_TOKEN=.*/, `AMAZON_REFRESH_TOKEN=${refreshToken}`)
      .replace(/AMAZON_REGION=.*/, `AMAZON_REGION=${region}`)
      .replace(/AMAZON_MARKETPLACE_ID=.*/, `AMAZON_MARKETPLACE_ID=${marketplaceId}`);

    fs.writeFileSync(envPath, envContent);

    console.log('✅ File .env aggiornato!\n');
    console.log('🎉 Setup completato! Ora puoi:');
    console.log('   1. Riavviare il server (se già in esecuzione)');
    console.log('   2. Visitare http://localhost:3000');
    console.log('   3. Cliccare su "Sync Data" per importare i tuoi dati Amazon\n');

  } catch (error) {
    console.error('❌ Errore durante la creazione dell\'account:', error.message);
    console.error('\nDettagli:', error);
  } finally {
    await prisma.$disconnect();
    rl.close();
  }
}

main().catch((error) => {
  console.error('Errore fatale:', error);
  process.exit(1);
});
